version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "3000:3000"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/deploy-fly
      - ~/.ssh/id_rsa:/.ssh/id_rsa
    ports:
      - "4000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  db-volume:
    driver: local
